### ISSUE TITLE
Fix the width for the Status Flow Chart

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#240]
For https://thefive.sabic.uberspace.de/blog/list?status=!=closed
```css
#additionalText img { width: 100% }
```
Ref.: #234
