### ISSUE TITLE
Highlight the link "translate from" for my languages

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#246]
Example assuming that my language is DE:
```css
mark a[href*=DE] { color: red; font-weight: bold; }
```
Result:
![osmbc-translatefrom-red](https://cloud.githubusercontent.com/assets/957501/12076509/25a0f51a-b18c-11e5-96fd-e7355ae7b9bb.png)

Although I already have this "feature" with a Stylish... in testing.

---

**My [Stylish] "OSMBC ‒ translate from EN"**
```css
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document regexp("http.*://thefive.sabic.uberspace.de/blog/.*style=translation.*") {
  mark a[href*=EN] , mark a[href*=ES] { color: red; font-weight: bold; }
}
```
[Stylish]: https://addons.mozilla.org/pt-BR/firefox/addon/stylish/?src=userprofile

**_Update_ ‒ Jan 14, 2016 / 19h (UTC-3)**

The OSMBC was updated in last days, and now the code of my Stylish is updated also:
```css
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document regexp("http.*://thefive.sabic.uberspace.de/blog/.*style=TRANSLATION") {
  mark a[href*=EN] , mark a[href*=ES] { color: red; font-weight: bold; }
}
```
